# This is a basic workflow to help you get started with Actions

name: Build Android

# Controls when the workflow will run
on:
  create:
    tags:
      - v*
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:     
  release-apk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - run: flutter --version
    - run: flutter pub get
    - run: flutter test
    - run: flutter build apk --release
    - run: flutter build appbundle
    - run: mv build/app/outputs/flutter-apk/*.apk KGPassGen-android.apk
    - uses: actions/upload-artifact@v2
      with:
        name: built-android
        path: KGPassGen-android.apk
  upload-artifacts:
    runs-on: ubuntu-latest
    needs: [release-apk]
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: built-android
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "KGPassGen-android.apk"
          token: ${{ secrets.TOKEN }}
          allowUpdates: true
